### ISSUE TITLE
ChangeBaseUrlTo does not respect SetUserAgent

### ISSUE THREAD

**Issue by CumpsD** [dnsimple/dnsimple-csharp#21]
I was looking through the code and saw this:

https://github.com/dnsimple/dnsimple-csharp/blob/master/src/dnsimple/DNSimple.cs#L332-L337

It seems this bit resets the user agent back to the default: `RestClientWrapper.RestClient.UserAgent = DefaultUserAgent;`

Which means this order will fail:

```csharp
var r = new RestClientWrapper();
var client = new Client(r);

client.SetUserAgent("exira/1.0");
Console.WriteLine(r.RestClient.UserAgent);
client.ChangeBaseUrlTo("https://api.sandbox.dnsimple.com");
Console.WriteLine(r.RestClient.UserAgent);
```

While this will be ok:

```csharp
var r = new RestClientWrapper();
var client = new Client(r);

client.ChangeBaseUrlTo("https://api.sandbox.dnsimple.com");
Console.WriteLine(r.RestClient.UserAgent);
client.SetUserAgent("exira/1.0");
Console.WriteLine(r.RestClient.UserAgent);
```

I am passing in the `RestClientWrapper` to check the UserAgent being used. Because the `UserAgent` property on `Client` will not show it

**Comment by weppos** [comment]
Thanks for the report @CumpsD. At first glance, it seems an oversight, I can't find any reason why we should set/reset the agent on URL change. This behavior doesn't exist in any other client.

We'll take a look shortly.

**Comment by CumpsD** [comment]
Thanks 👍
