### ISSUE TITLE
The 'licenseUrl' element deprecated

### ISSUE THREAD

**Issue by OleMchls** [dnsimple/dnsimple-csharp#48]
When we were releasing the package to Nuget we saw the following error:

<img width="1280" alt="Screenshot 2021-04-22 at 17 40 41" src="https://user-images.githubusercontent.com/584259/115744395-d3dd9900-a392-11eb-8336-82ab12822f88.png">

ℹ️  https://github.com/NuGet/Home/issues/7509

**Comment by ggalmazor** [comment]
After taking a look, we didn't find any usage of the `licenseUrl` directly. Therefore it must be somewhere in the toolchain we're using, which means we can't do much about it.

**Comment by DXTimer** [comment]
It no longer appears to be an issue. Closing.
