### ISSUE TITLE
Feature Request: Allow User to Moq Client Class Inner Service Classes and Their Methods

### ISSUE THREAD

**Issue by SProfession** [dnsimple/dnsimple-csharp#55]
I just started using this DnSimple library and while trying to write unit tests, was having issues creating a Moq of the inner service class' and their methods. Is there a way to doing this, or would it be possible to get this created as a feature? The reason being, I would like to test my application in isolation and not have to rely on calls outwards to your sandbox API for every unit test.

**Comment by ggalmazor** [comment]
Thanks for your suggestion, @SProfession! We have added it to our backlog so that we can consider it for future enhancements.

In any case, we'll be happy to review any PR you want to submit with the changes you'd like to see ;)

**Comment by DXTimer** [comment]
Closing for now if you have more feedback on the feature request feel free to comment and reopen it.
